set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g mouse on
set -g base-index 1                         
setw -g pane-base-index 1


bind-key -n C-n new-window -c "#{pane_current_path}"

bind-key -n C-w confirm-before -p " (y/n)" kill-window

bind-key -n C-Left  previous-window
bind-key -n C-Right next-window

bind-key -n C-S-Right if-shell "tmux list-sessions | grep -q v" "switch-client -n" "new-session -d -s General; switch-client -t General"
bind-key -n C-S-Left if-shell "tmux list-sessions | grep -q v" "switch-client -p" "new-session -d -s General; switch-client -t General"


set-option -g status-position top
set -g status-style bg=#1a1b26,fg=#a9b1d6

set -g status-left "#[fg=#1a1b26,bg=#7aa2f7,bold] 󰖼 #S #[fg=#7aa2f7,bg=#24283b,nobold] #(tmux ls | wc -l) 󱂬 "
set -g status-left-length 30

set -g status-right "#[fg=#565f89,bg=default] %H:%M │ %d-%b "
set -g window-status-format "#[fg=#565f89,bg=#24283b] #I:#W "

set -g window-status-current-format "#[fg=#7aa2f7,bg=#1f2335,bold] #I:#W #[fg=#7aa2f7,none]●"

set -g window-status-separator " "

set -g pane-border-style fg=#24283b
set -g pane-active-border-style fg=#7aa2f7

# msg xd
set -g message-style bg=#7aa2f7,fg=#1a1b26,bold
